[package]
name = "xsz"
version = "0.1.0"
edition = "2021"

[dependencies]
async-task = "4.7.1"
futures-lite = "2.6.0"
just-getopt = "1.4.1"
kanal = "0.1.0"
mimalloc = "0.1.44"
nohash = "0.2.0"
num_cpus = "1.16.0"
rustix = { version = "1.0.3", features = [ "fs" ] }

[profile]
[profile.dev.package."*"]
opt-level = "s"
debug = 0
split-debuginfo = "unpacked"
[profile.release]
opt-level = "s"
codegen-units = 1
debug = 0
lto = true
strip = "symbols"
panic = "abort"
