[package]
name = "xsz"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
crossbeam = "0.8.4"
mimalloc = "0.1.43"
nohash = "0.2.0"
parking_lot = "0.12.3"
replace_with = "0.1.7"
rustix = {version = "0.38.43", features = ["fs"]}
smol = "2.0.2"

[profile]
[profile.dev.package."*"]
opt-level = "s"
debug = 0
[profile.release]
codegen-units = 1
debug = 0
lto = true
strip = "debuginfo"
