[package]
name = "xsz"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
async-task = "4.7.1"
futures-lite = "2.6.0"
just-getopt = "1.2.0"
mimalloc = "0.1.43"
nohash = "0.2.0"
rustix = {version = "0.38.43", features = ["fs"]}

[profile]
[profile.dev.package."*"]
opt-level = "s"
debug = 0
[profile.release]
codegen-units = 1
debug = 0
lto = true
strip = "debuginfo"
